services:
  - type: web
    name: ephimero
    env: java
    plan: free
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/ephimero-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080